#!/usr/bin/env sh
# See the LICENSE file for copyright and license details.

FUNCPATH="./func"
VERSION="git"

usage() {
	cat <<EOF
${0##*/} [options]

  Options:
    d      Use the default configuration
    n      Print to stdout instead of the bar
    x      Kill existing sb instance
    h      Print this help and exit
    v      Print version number and exit

${0##*/}-$VERSION
2019-2020 (c) Cem Keylan
EOF
exit 0
}

case "$1" in 
    d) noconfig=1 ;;
    v) printf '%s\n' "${0##*/}-$VERSION"; exit 0 ;; 
    n) nobar=1 ;; 
    x) ! [ -e "/tmp/sb-$USER.pid" ] && \
    	printf "There is no running instance of sb\\n" && exit 1
    kill "$(cat "/tmp/sb-$USER.pid")"; rm "/tmp/sb-$USER.pid"; exit 0 
    ;; 
    *) usage ;;
esac


[ -z "$DELIMETER" ] && DELIMETER="|"
[ "$noconfig" -eq 0 ] && [ -e "$HOME/.config/sbrc" ] && . "$HOME/.config/sbrc"
[ -z "$SLEEPTIME" ] && SLEEPTIME="1"

for func in "$FUNCPATH/"* ; do [ -f "$func" ] && . "$func"; done
for func in "$HOME/.config/sbfunc/"* ; do
	[ -f "$func" ] && . "$func" ; done
if [ -z "$nobar" ]; then
	if [ -e "/tmp/sb-$USER.pid" ] ; then
		[ -z "$KILLEXISTING" ] && printf "ERROR: sb is already running\\nIf you think otherwise, remove /tmp/sb-$USER.pid manually.\\n" && exit 1
		kill "$(cat "/tmp/sb-$USER.pid")" 2>/dev/null
	fi
	printf "$$\\n" > "/tmp/sb-$USER.pid"
fi

if ! command -V bar >/dev/null 2>&1; then
	bar() {
		brightness
		pulseaudio
		battery
		DELIMETER=";" datetime
		storage
		storage /home
		ram
		nightmode
		gethostname
		showmpd
	}
fi

[ -z "$nobar" ] && while true; do xsetroot -name " $(bar)"; sleep "$SLEEPTIME"; done && exit 0
while true; do bar; sleep "$SLEEPTIME"; clear; done
