.TH "SBRC" "5" "sb-vnumber" "" ""
.hy
.SH NAME
.PP
sbrc - define functions to run for \f[B]sb\f[R](1)
.SH DESCRIPTION
.PP
sbrc is a file that can be added to customize the way \f[B]sb\f[R]
functions.
.PP
Currently, the variables are,
.TP
.B \f[B]NEWMAILDIR\f[R]
this is where new mails are stored on your computer,
e.g.\ \[ti]/.local/share/mail/foo/INBOW/new
.TP
.B \f[B]BATTERY\f[R]
this is the name of your batter, usually \f[B]BAT0\f[R]
.TP
.B \f[B]DATE\f[R]
the way you would like to see date.
see \f[B]date\f[R](1) for more details.
.TP
.B \f[B]SLEEPTIME\f[R]
refresh interval (in seconds)
.SH BAR FUNCTION
.PP
In the configuration, you can edit the \f[B]bar()\f[R] function, which
you can fill with the modules, see sbrc.example for more details
.SH BAR MODULES
.TP
.B \f[B]battery\f[R]
displays battery state and capacity
.TP
.B \f[B]brightness\f[R]
displays screen brightness percentage
.TP
.B \f[B]datetime\f[R]
displays datetime in requested format
.TP
.B \f[B]gethostname\f[R]
displays host name
.TP
.B \f[B]ipv4\f[R]
shows ipv4 address, requires interface name as argument
.TP
.B \f[B]mail\f[R]
displays number of new mail, requires \f[B]NEWMAILDIR\f[R] to be set
.TP
.B \f[B]nightmode\f[R]
displays CARBS nightmode information
.TP
.B \f[B]pulseaudio\f[R]
displays volume information from pulseaudio
.TP
.B \f[B]ram\f[R]
displays ram percentage
.TP
.B \f[B]showmpd\f[R]
displays current song, if any
.TP
.B \f[B]ssid\f[R]
displays connected wireless ssid, requires interface name as argument
.TP
.B \f[B]storage\f[R]
displays used/total disk space in GB, takes arguments for directories,
\f[B]e.g.\ storage /home\f[R]
.SH SEE ALSO
.PP
\f[B]sb\f[R](1)
.SH AUTHORS
Cem Keylan.
